/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Latihan4;

/**
 *
 * @author yusri
 */
public class Latihan4 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan4
     */
    public Latihan4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        BiodataSiswa = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Absen = new javax.swing.JTextField();
        Button1 = new javax.swing.JRadioButton();
        Button2 = new javax.swing.JRadioButton();
        Hobi1 = new javax.swing.JCheckBox();
        Hobi2 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Hapus = new javax.swing.JToggleButton();
        Submit = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        HASIL = new javax.swing.JTextArea();
        Hobi3 = new javax.swing.JCheckBox();
        Hobi4 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BiodataSiswa.setText("Biodata Siswa");
        getContentPane().add(BiodataSiswa);
        BiodataSiswa.setBounds(126, 11, 102, 14);
        getContentPane().add(Nama);
        Nama.setBounds(84, 26, 110, 30);
        getContentPane().add(Absen);
        Absen.setBounds(87, 62, 107, 30);

        Button1.setText("RPL");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button1);
        Button1.setBounds(97, 100, 69, 30);

        Button2.setText("TKJ");
        getContentPane().add(Button2);
        Button2.setBounds(166, 100, 52, 30);

        Hobi1.setText("Programing");
        getContentPane().add(Hobi1);
        Hobi1.setBounds(90, 133, 120, 30);

        Hobi2.setText("Gamer");
        Hobi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hobi2ActionPerformed(evt);
            }
        });
        getContentPane().add(Hobi2);
        Hobi2.setBounds(90, 160, 120, 30);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));
        jPanel1.setLayout(null);

        jLabel1.setText("Nama");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 40, 40, 10);

        jLabel2.setText("Absen");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 60, 40, 14);

        jLabel3.setText("Jurusan");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 50, 14);

        jLabel4.setText("Hobi");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 140, 40, 14);

        jLabel5.setText("Hasil");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 240, 40, 14);

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        jPanel1.add(Hapus);
        Hapus.setBounds(160, 200, 66, 23);

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit);
        Submit.setBounds(70, 200, 82, 23);

        jToggleButton3.setText("Exit");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3);
        jToggleButton3.setBounds(240, 200, 74, 23);

        HASIL.setColumns(20);
        HASIL.setRows(5);
        jScrollPane1.setViewportView(HASIL);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(90, 230, 213, 76);

        Hobi3.setText("Renang");
        jPanel1.add(Hobi3);
        Hobi3.setBounds(210, 130, 130, 30);

        Hobi4.setText("Nonton ");
        Hobi4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hobi4ActionPerformed(evt);
            }
        });
        jPanel1.add(Hobi4);
        Hobi4.setBounds(210, 160, 130, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button1ActionPerformed

    private void Hobi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hobi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hobi2ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String nama=Nama.getText();
        String absen=Absen.getText();
        String jurusan;
        String hobi="";
        
        if (Button1.isSelected()) {
            jurusan="RPL";
        }else if(Button2.isSelected()){
            jurusan="TKJ";
        }else
            jurusan="";
        
        if (Hobi1.isSelected()) {
            hobi+=Hobi1.getText()+",";
        }if (Hobi2.isSelected()) {
            hobi+=Hobi2.getText()+",'";
        }if (Hobi3.isSelected()) {
            hobi+=Hobi3.getText()+",";
        }if (Hobi4.isSelected()) {
            hobi+=Hobi4.getText()+",";
        }
        HASIL.setText("Nama Siswa:"+nama+"\nAbsen Siswa:"+absen+"\nJurusan Anda:"+jurusan+"\nHobi Anda:"+hobi);
    }//GEN-LAST:event_SubmitActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
       HASIL.setText("");
       Nama.setText("");
       Absen.setText("");
       buttonGroup1.clearSelection();
       Hobi1.setSelected(false);
       Hobi2.setSelected(false);
       Hobi3.setSelected(false);
       Hobi4.setSelected(false);
    }//GEN-LAST:event_HapusActionPerformed

    private void Hobi4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hobi4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hobi4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen;
    private javax.swing.JLabel BiodataSiswa;
    private javax.swing.JRadioButton Button1;
    private javax.swing.JRadioButton Button2;
    private javax.swing.JTextArea HASIL;
    private javax.swing.JToggleButton Hapus;
    private javax.swing.JCheckBox Hobi1;
    private javax.swing.JCheckBox Hobi2;
    private javax.swing.JCheckBox Hobi3;
    private javax.swing.JCheckBox Hobi4;
    private javax.swing.JTextField Nama;
    private javax.swing.JToggleButton Submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
